url: "https://webecome.family"
baseurl: ""

title: Gillian & Lisandro
description: |
  Gillian and Lisandro become family.
owner: Gillian and Lisandro
first_published: 2021

collections:
  rsvp:
    output: true
    permalink: /:path

defaults:
  - scope:
      type: "rsvp"
    values:
      layout: "rsvp"

permalink: /:title

email: hey@webecome.family

markdown: kramdown
sass:
  style: compressed
