url: "https://webecome.family"
baseurl: ""

title: Gillian & Lisandro
description: |
  Gillian and Lisandro become family.
owner: Gillian and Lisandro
first_published: 2021

email: hey@webecome.family

markdown: kramdown
sass:
  style: compressed
