url: "https://webecome.family"
baseurl: ""

title: Gillian & Lisandro
description: |
  Another fine responsive  
  site template freebie  
  crafted by [HTML5 UP](http://html5up.net)
owner: Gillian and Lisandro
first_published: 2021

email: hey@webecome.family

markdown: kramdown
sass:
  style: compressed
